### ISSUE TITLE
Missing orders

### ISSUE THREAD

**Issue by nordanfors** [PaysonAB/PaysonCheckout2-Prestashop-1-6#6]
Sometimes an order is not created in prestashop but the transaction is visible in Payson admin. I have tried to find a fix but no luck. The only workaround I found so far was to find the matching cart object and manually convert it to an order in Prestashop backoffice. I am using Prestashop 1.6.1.10 and have now reverted to the Payson 1.0 API because of this.

**Comment by ifom** [comment]
Same here.
Orders/Payments come to Payson but not finalized in store and we need to pick up the carts and complete the orders manually. This has been an issue for a long time now. 

We even modded the Payson module (mod provided by Payson) to fix any issue with rounding for decimals (when using % discounts) but there are still issues with some orders behaving just as described with missing orders in PS admin but visible in Payson.

We run. PS 1.6.1.12 and Payson2.0 module 1.0.1.1 (modded)

Payson please fix this!
