### ISSUE TITLE
 Undefined index: iframeSizeHeightType  Undefined index: iframeSizeWidthType

### ISSUE THREAD

**Issue by superbolof** [PaysonAB/PaysonCheckout2-Prestashop-1-6#7]
Whenever I try to save settings these errors appear:

///////////////////////////////////////////////////////////////////
Notice på rad 192 i fil /***/modules/paysonCheckout2/paysonCheckout2.php
[8] Undefined index: iframeSizeWidthType

Notice på rad 194 i fil /***/modules/paysonCheckout2/paysonCheckout2.php
[8] Undefined index: iframeSizeHeightType
///////////////////////////////////////////////////////////////////

Hur kan jag få bukt med detta problem??
(how can I fix this problem?)

**Comment by oscar2014** [comment]
@superbolof 

Hej,

Vilken version av modulen och PrestaShop använder du?

Skicka gärna svaret till integration@payson.se.

MVH
Payson AB | Integration
