### ISSUE TITLE
CartRule having free shipping prevent payment

### ISSUE THREAD

**Issue by doekia** [PaysonAB/PaysonCheckout2-Prestashop-1-6#9]
When a cart rule is providing free shipping the module refuse to accept payment:
alert -> Please try using a different payment method (redirect).
log says: Api errors\n\n\nMessage: HTTP status code: 400, Model validation failed. Parameter: \n\nMessage: \'Unit Price\' must be less than or equal to \'0\'. Parameter: Order.Items[1].UnitPrice\n\n\n

**Comment by PaysonAB** [comment]
The developer in charge of this module is on vacation and will be back in 2 weeks. He will to look into this when he gets back.
